// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contactless/iso14443_4a.proto

#include "contactless/iso14443_4a.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace contactless {
namespace iso14443_4a {
class RequestForAnswerToSelectDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RequestForAnswerToSelect> _instance;
} _RequestForAnswerToSelect_default_instance_;
class AnswerToSelectDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<AnswerToSelect> _instance;
} _AnswerToSelect_default_instance_;
}  // namespace iso14443_4a
}  // namespace contactless
static void InitDefaultsscc_info_AnswerToSelect_contactless_2fiso14443_5f4a_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::contactless::iso14443_4a::_AnswerToSelect_default_instance_;
    new (ptr) ::contactless::iso14443_4a::AnswerToSelect();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::contactless::iso14443_4a::AnswerToSelect::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_AnswerToSelect_contactless_2fiso14443_5f4a_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_AnswerToSelect_contactless_2fiso14443_5f4a_2eproto}, {}};

static void InitDefaultsscc_info_RequestForAnswerToSelect_contactless_2fiso14443_5f4a_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::contactless::iso14443_4a::_RequestForAnswerToSelect_default_instance_;
    new (ptr) ::contactless::iso14443_4a::RequestForAnswerToSelect();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::contactless::iso14443_4a::RequestForAnswerToSelect::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_RequestForAnswerToSelect_contactless_2fiso14443_5f4a_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_RequestForAnswerToSelect_contactless_2fiso14443_5f4a_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_contactless_2fiso14443_5f4a_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_contactless_2fiso14443_5f4a_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_contactless_2fiso14443_5f4a_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_contactless_2fiso14443_5f4a_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::contactless::iso14443_4a::RequestForAnswerToSelect, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::contactless::iso14443_4a::RequestForAnswerToSelect, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::contactless::iso14443_4a::AnswerToSelect, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::contactless::iso14443_4a::AnswerToSelect, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::contactless::iso14443_4a::AnswerToSelect, data_),
  0,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 5, sizeof(::contactless::iso14443_4a::RequestForAnswerToSelect)},
  { 5, 11, sizeof(::contactless::iso14443_4a::AnswerToSelect)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::contactless::iso14443_4a::_RequestForAnswerToSelect_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::contactless::iso14443_4a::_AnswerToSelect_default_instance_),
};

const char descriptor_table_protodef_contactless_2fiso14443_5f4a_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\035contactless/iso14443_4a.proto\022\027contact"
  "less.iso14443_4a\"\032\n\030RequestForAnswerToSe"
  "lect\"\036\n\016AnswerToSelect\022\014\n\004data\030\001 \002(\014"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_contactless_2fiso14443_5f4a_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_contactless_2fiso14443_5f4a_2eproto_sccs[2] = {
  &scc_info_AnswerToSelect_contactless_2fiso14443_5f4a_2eproto.base,
  &scc_info_RequestForAnswerToSelect_contactless_2fiso14443_5f4a_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_contactless_2fiso14443_5f4a_2eproto_once;
static bool descriptor_table_contactless_2fiso14443_5f4a_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_contactless_2fiso14443_5f4a_2eproto = {
  &descriptor_table_contactless_2fiso14443_5f4a_2eproto_initialized, descriptor_table_protodef_contactless_2fiso14443_5f4a_2eproto, "contactless/iso14443_4a.proto", 116,
  &descriptor_table_contactless_2fiso14443_5f4a_2eproto_once, descriptor_table_contactless_2fiso14443_5f4a_2eproto_sccs, descriptor_table_contactless_2fiso14443_5f4a_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_contactless_2fiso14443_5f4a_2eproto::offsets,
  file_level_metadata_contactless_2fiso14443_5f4a_2eproto, 2, file_level_enum_descriptors_contactless_2fiso14443_5f4a_2eproto, file_level_service_descriptors_contactless_2fiso14443_5f4a_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_contactless_2fiso14443_5f4a_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_contactless_2fiso14443_5f4a_2eproto), true);
namespace contactless {
namespace iso14443_4a {

// ===================================================================

void RequestForAnswerToSelect::InitAsDefaultInstance() {
}
class RequestForAnswerToSelect::_Internal {
 public:
  using HasBits = decltype(std::declval<RequestForAnswerToSelect>()._has_bits_);
};

RequestForAnswerToSelect::RequestForAnswerToSelect()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:contactless.iso14443_4a.RequestForAnswerToSelect)
}
RequestForAnswerToSelect::RequestForAnswerToSelect(const RequestForAnswerToSelect& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:contactless.iso14443_4a.RequestForAnswerToSelect)
}

void RequestForAnswerToSelect::SharedCtor() {
}

RequestForAnswerToSelect::~RequestForAnswerToSelect() {
  // @@protoc_insertion_point(destructor:contactless.iso14443_4a.RequestForAnswerToSelect)
  SharedDtor();
}

void RequestForAnswerToSelect::SharedDtor() {
}

void RequestForAnswerToSelect::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RequestForAnswerToSelect& RequestForAnswerToSelect::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_RequestForAnswerToSelect_contactless_2fiso14443_5f4a_2eproto.base);
  return *internal_default_instance();
}


void RequestForAnswerToSelect::Clear() {
// @@protoc_insertion_point(message_clear_start:contactless.iso14443_4a.RequestForAnswerToSelect)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* RequestForAnswerToSelect::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RequestForAnswerToSelect::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:contactless.iso14443_4a.RequestForAnswerToSelect)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:contactless.iso14443_4a.RequestForAnswerToSelect)
  return target;
}

size_t RequestForAnswerToSelect::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:contactless.iso14443_4a.RequestForAnswerToSelect)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RequestForAnswerToSelect::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:contactless.iso14443_4a.RequestForAnswerToSelect)
  GOOGLE_DCHECK_NE(&from, this);
  const RequestForAnswerToSelect* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RequestForAnswerToSelect>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:contactless.iso14443_4a.RequestForAnswerToSelect)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:contactless.iso14443_4a.RequestForAnswerToSelect)
    MergeFrom(*source);
  }
}

void RequestForAnswerToSelect::MergeFrom(const RequestForAnswerToSelect& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:contactless.iso14443_4a.RequestForAnswerToSelect)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void RequestForAnswerToSelect::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:contactless.iso14443_4a.RequestForAnswerToSelect)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RequestForAnswerToSelect::CopyFrom(const RequestForAnswerToSelect& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:contactless.iso14443_4a.RequestForAnswerToSelect)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RequestForAnswerToSelect::IsInitialized() const {
  return true;
}

void RequestForAnswerToSelect::InternalSwap(RequestForAnswerToSelect* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata RequestForAnswerToSelect::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void AnswerToSelect::InitAsDefaultInstance() {
}
class AnswerToSelect::_Internal {
 public:
  using HasBits = decltype(std::declval<AnswerToSelect>()._has_bits_);
  static void set_has_data(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

AnswerToSelect::AnswerToSelect()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:contactless.iso14443_4a.AnswerToSelect)
}
AnswerToSelect::AnswerToSelect(const AnswerToSelect& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  data_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_data()) {
    data_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
  // @@protoc_insertion_point(copy_constructor:contactless.iso14443_4a.AnswerToSelect)
}

void AnswerToSelect::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_AnswerToSelect_contactless_2fiso14443_5f4a_2eproto.base);
  data_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

AnswerToSelect::~AnswerToSelect() {
  // @@protoc_insertion_point(destructor:contactless.iso14443_4a.AnswerToSelect)
  SharedDtor();
}

void AnswerToSelect::SharedDtor() {
  data_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void AnswerToSelect::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const AnswerToSelect& AnswerToSelect::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_AnswerToSelect_contactless_2fiso14443_5f4a_2eproto.base);
  return *internal_default_instance();
}


void AnswerToSelect::Clear() {
// @@protoc_insertion_point(message_clear_start:contactless.iso14443_4a.AnswerToSelect)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    data_.ClearNonDefaultToEmptyNoArena();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* AnswerToSelect::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required bytes data = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_data();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* AnswerToSelect::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:contactless.iso14443_4a.AnswerToSelect)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required bytes data = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:contactless.iso14443_4a.AnswerToSelect)
  return target;
}

size_t AnswerToSelect::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:contactless.iso14443_4a.AnswerToSelect)
  size_t total_size = 0;

  // required bytes data = 1;
  if (_internal_has_data()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_data());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AnswerToSelect::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:contactless.iso14443_4a.AnswerToSelect)
  GOOGLE_DCHECK_NE(&from, this);
  const AnswerToSelect* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<AnswerToSelect>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:contactless.iso14443_4a.AnswerToSelect)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:contactless.iso14443_4a.AnswerToSelect)
    MergeFrom(*source);
  }
}

void AnswerToSelect::MergeFrom(const AnswerToSelect& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:contactless.iso14443_4a.AnswerToSelect)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_data()) {
    _has_bits_[0] |= 0x00000001u;
    data_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
}

void AnswerToSelect::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:contactless.iso14443_4a.AnswerToSelect)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AnswerToSelect::CopyFrom(const AnswerToSelect& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:contactless.iso14443_4a.AnswerToSelect)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AnswerToSelect::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  return true;
}

void AnswerToSelect::InternalSwap(AnswerToSelect* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  data_.Swap(&other->data_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::PROTOBUF_NAMESPACE_ID::Metadata AnswerToSelect::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace iso14443_4a
}  // namespace contactless
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::contactless::iso14443_4a::RequestForAnswerToSelect* Arena::CreateMaybeMessage< ::contactless::iso14443_4a::RequestForAnswerToSelect >(Arena* arena) {
  return Arena::CreateInternal< ::contactless::iso14443_4a::RequestForAnswerToSelect >(arena);
}
template<> PROTOBUF_NOINLINE ::contactless::iso14443_4a::AnswerToSelect* Arena::CreateMaybeMessage< ::contactless::iso14443_4a::AnswerToSelect >(Arena* arena) {
  return Arena::CreateInternal< ::contactless::iso14443_4a::AnswerToSelect >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
