// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contact/iso7816_4.proto

#include "contact/iso7816_4.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace contact {
namespace iso7816_4 {
class TransmitApduDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<TransmitApdu> _instance;
} _TransmitApdu_default_instance_;
class ResponseApduDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ResponseApdu> _instance;
} _ResponseApdu_default_instance_;
}  // namespace iso7816_4
}  // namespace contact
static void InitDefaultsscc_info_ResponseApdu_contact_2fiso7816_5f4_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::contact::iso7816_4::_ResponseApdu_default_instance_;
    new (ptr) ::contact::iso7816_4::ResponseApdu();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::contact::iso7816_4::ResponseApdu::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ResponseApdu_contact_2fiso7816_5f4_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ResponseApdu_contact_2fiso7816_5f4_2eproto}, {}};

static void InitDefaultsscc_info_TransmitApdu_contact_2fiso7816_5f4_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::contact::iso7816_4::_TransmitApdu_default_instance_;
    new (ptr) ::contact::iso7816_4::TransmitApdu();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::contact::iso7816_4::TransmitApdu::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_TransmitApdu_contact_2fiso7816_5f4_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_TransmitApdu_contact_2fiso7816_5f4_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_contact_2fiso7816_5f4_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_contact_2fiso7816_5f4_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_contact_2fiso7816_5f4_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_contact_2fiso7816_5f4_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::contact::iso7816_4::TransmitApdu, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::contact::iso7816_4::TransmitApdu, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::contact::iso7816_4::TransmitApdu, slot_),
  PROTOBUF_FIELD_OFFSET(::contact::iso7816_4::TransmitApdu, command_apdu_),
  1,
  0,
  PROTOBUF_FIELD_OFFSET(::contact::iso7816_4::ResponseApdu, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::contact::iso7816_4::ResponseApdu, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::contact::iso7816_4::ResponseApdu, body_),
  PROTOBUF_FIELD_OFFSET(::contact::iso7816_4::ResponseApdu, trailer_),
  0,
  1,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::contact::iso7816_4::TransmitApdu)},
  { 9, 16, sizeof(::contact::iso7816_4::ResponseApdu)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::contact::iso7816_4::_TransmitApdu_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::contact::iso7816_4::_ResponseApdu_default_instance_),
};

const char descriptor_table_protodef_contact_2fiso7816_5f4_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027contact/iso7816_4.proto\022\021contact.iso78"
  "16_4\032\027contact/card_slot.proto\"O\n\014Transmi"
  "tApdu\022)\n\004slot\030\001 \002(\0162\033.contact.card_slot."
  "CardSlot\022\024\n\014command_apdu\030\002 \002(\014\"-\n\014Respon"
  "seApdu\022\014\n\004body\030\001 \001(\014\022\017\n\007trailer\030\002 \002(\r"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_contact_2fiso7816_5f4_2eproto_deps[1] = {
  &::descriptor_table_contact_2fcard_5fslot_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_contact_2fiso7816_5f4_2eproto_sccs[2] = {
  &scc_info_ResponseApdu_contact_2fiso7816_5f4_2eproto.base,
  &scc_info_TransmitApdu_contact_2fiso7816_5f4_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_contact_2fiso7816_5f4_2eproto_once;
static bool descriptor_table_contact_2fiso7816_5f4_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_contact_2fiso7816_5f4_2eproto = {
  &descriptor_table_contact_2fiso7816_5f4_2eproto_initialized, descriptor_table_protodef_contact_2fiso7816_5f4_2eproto, "contact/iso7816_4.proto", 197,
  &descriptor_table_contact_2fiso7816_5f4_2eproto_once, descriptor_table_contact_2fiso7816_5f4_2eproto_sccs, descriptor_table_contact_2fiso7816_5f4_2eproto_deps, 2, 1,
  schemas, file_default_instances, TableStruct_contact_2fiso7816_5f4_2eproto::offsets,
  file_level_metadata_contact_2fiso7816_5f4_2eproto, 2, file_level_enum_descriptors_contact_2fiso7816_5f4_2eproto, file_level_service_descriptors_contact_2fiso7816_5f4_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_contact_2fiso7816_5f4_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_contact_2fiso7816_5f4_2eproto), true);
namespace contact {
namespace iso7816_4 {

// ===================================================================

void TransmitApdu::InitAsDefaultInstance() {
}
class TransmitApdu::_Internal {
 public:
  using HasBits = decltype(std::declval<TransmitApdu>()._has_bits_);
  static void set_has_slot(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_command_apdu(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

TransmitApdu::TransmitApdu()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:contact.iso7816_4.TransmitApdu)
}
TransmitApdu::TransmitApdu(const TransmitApdu& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  command_apdu_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_command_apdu()) {
    command_apdu_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.command_apdu_);
  }
  slot_ = from.slot_;
  // @@protoc_insertion_point(copy_constructor:contact.iso7816_4.TransmitApdu)
}

void TransmitApdu::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_TransmitApdu_contact_2fiso7816_5f4_2eproto.base);
  command_apdu_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  slot_ = 0;
}

TransmitApdu::~TransmitApdu() {
  // @@protoc_insertion_point(destructor:contact.iso7816_4.TransmitApdu)
  SharedDtor();
}

void TransmitApdu::SharedDtor() {
  command_apdu_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void TransmitApdu::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TransmitApdu& TransmitApdu::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_TransmitApdu_contact_2fiso7816_5f4_2eproto.base);
  return *internal_default_instance();
}


void TransmitApdu::Clear() {
// @@protoc_insertion_point(message_clear_start:contact.iso7816_4.TransmitApdu)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    command_apdu_.ClearNonDefaultToEmptyNoArena();
  }
  slot_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* TransmitApdu::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required .contact.card_slot.CardSlot slot = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::contact::card_slot::CardSlot_IsValid(val))) {
            _internal_set_slot(static_cast<::contact::card_slot::CardSlot>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(1, val, mutable_unknown_fields());
          }
        } else goto handle_unusual;
        continue;
      // required bytes command_apdu = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_command_apdu();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* TransmitApdu::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:contact.iso7816_4.TransmitApdu)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .contact.card_slot.CardSlot slot = 1;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_slot(), target);
  }

  // required bytes command_apdu = 2;
  if (cached_has_bits & 0x00000001u) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_command_apdu(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:contact.iso7816_4.TransmitApdu)
  return target;
}

size_t TransmitApdu::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:contact.iso7816_4.TransmitApdu)
  size_t total_size = 0;

  if (_internal_has_command_apdu()) {
    // required bytes command_apdu = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_command_apdu());
  }

  if (_internal_has_slot()) {
    // required .contact.card_slot.CardSlot slot = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_slot());
  }

  return total_size;
}
size_t TransmitApdu::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:contact.iso7816_4.TransmitApdu)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required bytes command_apdu = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_command_apdu());

    // required .contact.card_slot.CardSlot slot = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_slot());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TransmitApdu::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:contact.iso7816_4.TransmitApdu)
  GOOGLE_DCHECK_NE(&from, this);
  const TransmitApdu* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<TransmitApdu>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:contact.iso7816_4.TransmitApdu)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:contact.iso7816_4.TransmitApdu)
    MergeFrom(*source);
  }
}

void TransmitApdu::MergeFrom(const TransmitApdu& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:contact.iso7816_4.TransmitApdu)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _has_bits_[0] |= 0x00000001u;
      command_apdu_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.command_apdu_);
    }
    if (cached_has_bits & 0x00000002u) {
      slot_ = from.slot_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void TransmitApdu::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:contact.iso7816_4.TransmitApdu)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TransmitApdu::CopyFrom(const TransmitApdu& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:contact.iso7816_4.TransmitApdu)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TransmitApdu::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}

void TransmitApdu::InternalSwap(TransmitApdu* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  command_apdu_.Swap(&other->command_apdu_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(slot_, other->slot_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TransmitApdu::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ResponseApdu::InitAsDefaultInstance() {
}
class ResponseApdu::_Internal {
 public:
  using HasBits = decltype(std::declval<ResponseApdu>()._has_bits_);
  static void set_has_body(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_trailer(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

ResponseApdu::ResponseApdu()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:contact.iso7816_4.ResponseApdu)
}
ResponseApdu::ResponseApdu(const ResponseApdu& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  body_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_body()) {
    body_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.body_);
  }
  trailer_ = from.trailer_;
  // @@protoc_insertion_point(copy_constructor:contact.iso7816_4.ResponseApdu)
}

void ResponseApdu::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ResponseApdu_contact_2fiso7816_5f4_2eproto.base);
  body_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  trailer_ = 0u;
}

ResponseApdu::~ResponseApdu() {
  // @@protoc_insertion_point(destructor:contact.iso7816_4.ResponseApdu)
  SharedDtor();
}

void ResponseApdu::SharedDtor() {
  body_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ResponseApdu::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ResponseApdu& ResponseApdu::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ResponseApdu_contact_2fiso7816_5f4_2eproto.base);
  return *internal_default_instance();
}


void ResponseApdu::Clear() {
// @@protoc_insertion_point(message_clear_start:contact.iso7816_4.ResponseApdu)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    body_.ClearNonDefaultToEmptyNoArena();
  }
  trailer_ = 0u;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* ResponseApdu::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional bytes body = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_body();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required uint32 trailer = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _Internal::set_has_trailer(&has_bits);
          trailer_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ResponseApdu::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:contact.iso7816_4.ResponseApdu)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bytes body = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_body(), target);
  }

  // required uint32 trailer = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_trailer(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:contact.iso7816_4.ResponseApdu)
  return target;
}

size_t ResponseApdu::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:contact.iso7816_4.ResponseApdu)
  size_t total_size = 0;

  // required uint32 trailer = 2;
  if (_internal_has_trailer()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_trailer());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional bytes body = 1;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_body());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ResponseApdu::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:contact.iso7816_4.ResponseApdu)
  GOOGLE_DCHECK_NE(&from, this);
  const ResponseApdu* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ResponseApdu>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:contact.iso7816_4.ResponseApdu)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:contact.iso7816_4.ResponseApdu)
    MergeFrom(*source);
  }
}

void ResponseApdu::MergeFrom(const ResponseApdu& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:contact.iso7816_4.ResponseApdu)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _has_bits_[0] |= 0x00000001u;
      body_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.body_);
    }
    if (cached_has_bits & 0x00000002u) {
      trailer_ = from.trailer_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ResponseApdu::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:contact.iso7816_4.ResponseApdu)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ResponseApdu::CopyFrom(const ResponseApdu& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:contact.iso7816_4.ResponseApdu)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResponseApdu::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000002) != 0x00000002) return false;
  return true;
}

void ResponseApdu::InternalSwap(ResponseApdu* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  body_.Swap(&other->body_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(trailer_, other->trailer_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ResponseApdu::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace iso7816_4
}  // namespace contact
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::contact::iso7816_4::TransmitApdu* Arena::CreateMaybeMessage< ::contact::iso7816_4::TransmitApdu >(Arena* arena) {
  return Arena::CreateInternal< ::contact::iso7816_4::TransmitApdu >(arena);
}
template<> PROTOBUF_NOINLINE ::contact::iso7816_4::ResponseApdu* Arena::CreateMaybeMessage< ::contact::iso7816_4::ResponseApdu >(Arena* arena) {
  return Arena::CreateInternal< ::contact::iso7816_4::ResponseApdu >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
