// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mifare/ultralight/counter/increment.proto

#include "mifare/ultralight/counter/increment.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace mifare {
namespace ultralight {
namespace counter {
namespace increment {
class IncrementCounterDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<IncrementCounter> _instance;
} _IncrementCounter_default_instance_;
}  // namespace increment
}  // namespace counter
}  // namespace ultralight
}  // namespace mifare
static void InitDefaultsscc_info_IncrementCounter_mifare_2fultralight_2fcounter_2fincrement_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mifare::ultralight::counter::increment::_IncrementCounter_default_instance_;
    new (ptr) ::mifare::ultralight::counter::increment::IncrementCounter();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mifare::ultralight::counter::increment::IncrementCounter::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_IncrementCounter_mifare_2fultralight_2fcounter_2fincrement_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_IncrementCounter_mifare_2fultralight_2fcounter_2fincrement_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_mifare_2fultralight_2fcounter_2fincrement_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_mifare_2fultralight_2fcounter_2fincrement_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_mifare_2fultralight_2fcounter_2fincrement_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_mifare_2fultralight_2fcounter_2fincrement_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::mifare::ultralight::counter::increment::IncrementCounter, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::mifare::ultralight::counter::increment::IncrementCounter, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::mifare::ultralight::counter::increment::IncrementCounter, counter_number_),
  PROTOBUF_FIELD_OFFSET(::mifare::ultralight::counter::increment::IncrementCounter, operand_),
  0,
  1,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::mifare::ultralight::counter::increment::IncrementCounter)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::mifare::ultralight::counter::increment::_IncrementCounter_default_instance_),
};

const char descriptor_table_protodef_mifare_2fultralight_2fcounter_2fincrement_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n)mifare/ultralight/counter/increment.pr"
  "oto\022#mifare.ultralight.counter.increment"
  "\032&mifare/ultralight/counter/number.proto"
  "\"l\n\020IncrementCounter\022G\n\016counter_number\030\001"
  " \002(\0162/.mifare.ultralight.counter.number."
  "CounterNumber\022\017\n\007operand\030\002 \002(\r"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_mifare_2fultralight_2fcounter_2fincrement_2eproto_deps[1] = {
  &::descriptor_table_mifare_2fultralight_2fcounter_2fnumber_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_mifare_2fultralight_2fcounter_2fincrement_2eproto_sccs[1] = {
  &scc_info_IncrementCounter_mifare_2fultralight_2fcounter_2fincrement_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_mifare_2fultralight_2fcounter_2fincrement_2eproto_once;
static bool descriptor_table_mifare_2fultralight_2fcounter_2fincrement_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mifare_2fultralight_2fcounter_2fincrement_2eproto = {
  &descriptor_table_mifare_2fultralight_2fcounter_2fincrement_2eproto_initialized, descriptor_table_protodef_mifare_2fultralight_2fcounter_2fincrement_2eproto, "mifare/ultralight/counter/increment.proto", 230,
  &descriptor_table_mifare_2fultralight_2fcounter_2fincrement_2eproto_once, descriptor_table_mifare_2fultralight_2fcounter_2fincrement_2eproto_sccs, descriptor_table_mifare_2fultralight_2fcounter_2fincrement_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_mifare_2fultralight_2fcounter_2fincrement_2eproto::offsets,
  file_level_metadata_mifare_2fultralight_2fcounter_2fincrement_2eproto, 1, file_level_enum_descriptors_mifare_2fultralight_2fcounter_2fincrement_2eproto, file_level_service_descriptors_mifare_2fultralight_2fcounter_2fincrement_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_mifare_2fultralight_2fcounter_2fincrement_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_mifare_2fultralight_2fcounter_2fincrement_2eproto), true);
namespace mifare {
namespace ultralight {
namespace counter {
namespace increment {

// ===================================================================

void IncrementCounter::InitAsDefaultInstance() {
}
class IncrementCounter::_Internal {
 public:
  using HasBits = decltype(std::declval<IncrementCounter>()._has_bits_);
  static void set_has_counter_number(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_operand(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

IncrementCounter::IncrementCounter()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:mifare.ultralight.counter.increment.IncrementCounter)
}
IncrementCounter::IncrementCounter(const IncrementCounter& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&counter_number_, &from.counter_number_,
    static_cast<size_t>(reinterpret_cast<char*>(&operand_) -
    reinterpret_cast<char*>(&counter_number_)) + sizeof(operand_));
  // @@protoc_insertion_point(copy_constructor:mifare.ultralight.counter.increment.IncrementCounter)
}

void IncrementCounter::SharedCtor() {
  ::memset(&counter_number_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&operand_) -
      reinterpret_cast<char*>(&counter_number_)) + sizeof(operand_));
}

IncrementCounter::~IncrementCounter() {
  // @@protoc_insertion_point(destructor:mifare.ultralight.counter.increment.IncrementCounter)
  SharedDtor();
}

void IncrementCounter::SharedDtor() {
}

void IncrementCounter::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const IncrementCounter& IncrementCounter::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_IncrementCounter_mifare_2fultralight_2fcounter_2fincrement_2eproto.base);
  return *internal_default_instance();
}


void IncrementCounter::Clear() {
// @@protoc_insertion_point(message_clear_start:mifare.ultralight.counter.increment.IncrementCounter)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    ::memset(&counter_number_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&operand_) -
        reinterpret_cast<char*>(&counter_number_)) + sizeof(operand_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* IncrementCounter::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required .mifare.ultralight.counter.number.CounterNumber counter_number = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::mifare::ultralight::counter::number::CounterNumber_IsValid(val))) {
            _internal_set_counter_number(static_cast<::mifare::ultralight::counter::number::CounterNumber>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(1, val, mutable_unknown_fields());
          }
        } else goto handle_unusual;
        continue;
      // required uint32 operand = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _Internal::set_has_operand(&has_bits);
          operand_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* IncrementCounter::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mifare.ultralight.counter.increment.IncrementCounter)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .mifare.ultralight.counter.number.CounterNumber counter_number = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_counter_number(), target);
  }

  // required uint32 operand = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_operand(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mifare.ultralight.counter.increment.IncrementCounter)
  return target;
}

size_t IncrementCounter::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:mifare.ultralight.counter.increment.IncrementCounter)
  size_t total_size = 0;

  if (_internal_has_counter_number()) {
    // required .mifare.ultralight.counter.number.CounterNumber counter_number = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_counter_number());
  }

  if (_internal_has_operand()) {
    // required uint32 operand = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_operand());
  }

  return total_size;
}
size_t IncrementCounter::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mifare.ultralight.counter.increment.IncrementCounter)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required .mifare.ultralight.counter.number.CounterNumber counter_number = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_counter_number());

    // required uint32 operand = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_operand());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void IncrementCounter::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mifare.ultralight.counter.increment.IncrementCounter)
  GOOGLE_DCHECK_NE(&from, this);
  const IncrementCounter* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<IncrementCounter>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mifare.ultralight.counter.increment.IncrementCounter)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mifare.ultralight.counter.increment.IncrementCounter)
    MergeFrom(*source);
  }
}

void IncrementCounter::MergeFrom(const IncrementCounter& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mifare.ultralight.counter.increment.IncrementCounter)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      counter_number_ = from.counter_number_;
    }
    if (cached_has_bits & 0x00000002u) {
      operand_ = from.operand_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void IncrementCounter::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mifare.ultralight.counter.increment.IncrementCounter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void IncrementCounter::CopyFrom(const IncrementCounter& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mifare.ultralight.counter.increment.IncrementCounter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IncrementCounter::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}

void IncrementCounter::InternalSwap(IncrementCounter* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(counter_number_, other->counter_number_);
  swap(operand_, other->operand_);
}

::PROTOBUF_NAMESPACE_ID::Metadata IncrementCounter::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace increment
}  // namespace counter
}  // namespace ultralight
}  // namespace mifare
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::mifare::ultralight::counter::increment::IncrementCounter* Arena::CreateMaybeMessage< ::mifare::ultralight::counter::increment::IncrementCounter >(Arena* arena) {
  return Arena::CreateInternal< ::mifare::ultralight::counter::increment::IncrementCounter >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
