// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cipurse/authorize_sam.proto

#include "cipurse/authorize_sam.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace cipurse {
namespace sam {
class AuthorizeHwSamDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<AuthorizeHwSam> _instance;
} _AuthorizeHwSam_default_instance_;
}  // namespace sam
}  // namespace cipurse
static void InitDefaultsscc_info_AuthorizeHwSam_cipurse_2fauthorize_5fsam_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::cipurse::sam::_AuthorizeHwSam_default_instance_;
    new (ptr) ::cipurse::sam::AuthorizeHwSam();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::cipurse::sam::AuthorizeHwSam::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_AuthorizeHwSam_cipurse_2fauthorize_5fsam_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_AuthorizeHwSam_cipurse_2fauthorize_5fsam_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_cipurse_2fauthorize_5fsam_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_cipurse_2fauthorize_5fsam_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_cipurse_2fauthorize_5fsam_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_cipurse_2fauthorize_5fsam_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::cipurse::sam::AuthorizeHwSam, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::cipurse::sam::AuthorizeHwSam, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::cipurse::sam::AuthorizeHwSam, slot_),
  PROTOBUF_FIELD_OFFSET(::cipurse::sam::AuthorizeHwSam, aid_),
  PROTOBUF_FIELD_OFFSET(::cipurse::sam::AuthorizeHwSam, password_),
  2,
  0,
  1,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, sizeof(::cipurse::sam::AuthorizeHwSam)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::cipurse::sam::_AuthorizeHwSam_default_instance_),
};

const char descriptor_table_protodef_cipurse_2fauthorize_5fsam_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\033cipurse/authorize_sam.proto\022\013cipurse.s"
  "am\032\027contact/card_slot.proto\"Z\n\016Authorize"
  "HwSam\022)\n\004slot\030\001 \002(\0162\033.contact.card_slot."
  "CardSlot\022\013\n\003aid\030\002 \002(\014\022\020\n\010password\030\003 \001(\014"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_cipurse_2fauthorize_5fsam_2eproto_deps[1] = {
  &::descriptor_table_contact_2fcard_5fslot_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_cipurse_2fauthorize_5fsam_2eproto_sccs[1] = {
  &scc_info_AuthorizeHwSam_cipurse_2fauthorize_5fsam_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_cipurse_2fauthorize_5fsam_2eproto_once;
static bool descriptor_table_cipurse_2fauthorize_5fsam_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_cipurse_2fauthorize_5fsam_2eproto = {
  &descriptor_table_cipurse_2fauthorize_5fsam_2eproto_initialized, descriptor_table_protodef_cipurse_2fauthorize_5fsam_2eproto, "cipurse/authorize_sam.proto", 159,
  &descriptor_table_cipurse_2fauthorize_5fsam_2eproto_once, descriptor_table_cipurse_2fauthorize_5fsam_2eproto_sccs, descriptor_table_cipurse_2fauthorize_5fsam_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_cipurse_2fauthorize_5fsam_2eproto::offsets,
  file_level_metadata_cipurse_2fauthorize_5fsam_2eproto, 1, file_level_enum_descriptors_cipurse_2fauthorize_5fsam_2eproto, file_level_service_descriptors_cipurse_2fauthorize_5fsam_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_cipurse_2fauthorize_5fsam_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_cipurse_2fauthorize_5fsam_2eproto), true);
namespace cipurse {
namespace sam {

// ===================================================================

void AuthorizeHwSam::InitAsDefaultInstance() {
}
class AuthorizeHwSam::_Internal {
 public:
  using HasBits = decltype(std::declval<AuthorizeHwSam>()._has_bits_);
  static void set_has_slot(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_aid(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_password(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

AuthorizeHwSam::AuthorizeHwSam()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:cipurse.sam.AuthorizeHwSam)
}
AuthorizeHwSam::AuthorizeHwSam(const AuthorizeHwSam& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  aid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_aid()) {
    aid_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.aid_);
  }
  password_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_password()) {
    password_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.password_);
  }
  slot_ = from.slot_;
  // @@protoc_insertion_point(copy_constructor:cipurse.sam.AuthorizeHwSam)
}

void AuthorizeHwSam::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_AuthorizeHwSam_cipurse_2fauthorize_5fsam_2eproto.base);
  aid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  password_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  slot_ = 0;
}

AuthorizeHwSam::~AuthorizeHwSam() {
  // @@protoc_insertion_point(destructor:cipurse.sam.AuthorizeHwSam)
  SharedDtor();
}

void AuthorizeHwSam::SharedDtor() {
  aid_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  password_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void AuthorizeHwSam::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const AuthorizeHwSam& AuthorizeHwSam::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_AuthorizeHwSam_cipurse_2fauthorize_5fsam_2eproto.base);
  return *internal_default_instance();
}


void AuthorizeHwSam::Clear() {
// @@protoc_insertion_point(message_clear_start:cipurse.sam.AuthorizeHwSam)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      aid_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      password_.ClearNonDefaultToEmptyNoArena();
    }
  }
  slot_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* AuthorizeHwSam::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required .contact.card_slot.CardSlot slot = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::contact::card_slot::CardSlot_IsValid(val))) {
            _internal_set_slot(static_cast<::contact::card_slot::CardSlot>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(1, val, mutable_unknown_fields());
          }
        } else goto handle_unusual;
        continue;
      // required bytes aid = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_aid();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bytes password = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_password();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* AuthorizeHwSam::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cipurse.sam.AuthorizeHwSam)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .contact.card_slot.CardSlot slot = 1;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_slot(), target);
  }

  // required bytes aid = 2;
  if (cached_has_bits & 0x00000001u) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_aid(), target);
  }

  // optional bytes password = 3;
  if (cached_has_bits & 0x00000002u) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_password(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cipurse.sam.AuthorizeHwSam)
  return target;
}

size_t AuthorizeHwSam::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:cipurse.sam.AuthorizeHwSam)
  size_t total_size = 0;

  if (_internal_has_aid()) {
    // required bytes aid = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_aid());
  }

  if (_internal_has_slot()) {
    // required .contact.card_slot.CardSlot slot = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_slot());
  }

  return total_size;
}
size_t AuthorizeHwSam::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cipurse.sam.AuthorizeHwSam)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x00000005) ^ 0x00000005) == 0) {  // All required fields are present.
    // required bytes aid = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_aid());

    // required .contact.card_slot.CardSlot slot = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_slot());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional bytes password = 3;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000002u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_password());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AuthorizeHwSam::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:cipurse.sam.AuthorizeHwSam)
  GOOGLE_DCHECK_NE(&from, this);
  const AuthorizeHwSam* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<AuthorizeHwSam>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:cipurse.sam.AuthorizeHwSam)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:cipurse.sam.AuthorizeHwSam)
    MergeFrom(*source);
  }
}

void AuthorizeHwSam::MergeFrom(const AuthorizeHwSam& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cipurse.sam.AuthorizeHwSam)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _has_bits_[0] |= 0x00000001u;
      aid_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.aid_);
    }
    if (cached_has_bits & 0x00000002u) {
      _has_bits_[0] |= 0x00000002u;
      password_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.password_);
    }
    if (cached_has_bits & 0x00000004u) {
      slot_ = from.slot_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void AuthorizeHwSam::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:cipurse.sam.AuthorizeHwSam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AuthorizeHwSam::CopyFrom(const AuthorizeHwSam& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cipurse.sam.AuthorizeHwSam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AuthorizeHwSam::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000005) != 0x00000005) return false;
  return true;
}

void AuthorizeHwSam::InternalSwap(AuthorizeHwSam* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  aid_.Swap(&other->aid_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  password_.Swap(&other->password_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(slot_, other->slot_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AuthorizeHwSam::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace sam
}  // namespace cipurse
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::cipurse::sam::AuthorizeHwSam* Arena::CreateMaybeMessage< ::cipurse::sam::AuthorizeHwSam >(Arena* arena) {
  return Arena::CreateInternal< ::cipurse::sam::AuthorizeHwSam >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
