// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gui/text_id.proto

#include "gui/text_id.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace gui {
namespace text_id {
}  // namespace text_id
}  // namespace gui
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_gui_2ftext_5fid_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_gui_2ftext_5fid_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_gui_2ftext_5fid_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_gui_2ftext_5fid_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_gui_2ftext_5fid_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021gui/text_id.proto\022\013gui.text_id*\221\001\n\006Tex"
  "tId\022\016\n\nIP_ADDRESS\020\000\022\031\n\025ETHERNET_PORT1_ST"
  "ATUS\020\001\022\031\n\025ETHERNET_PORT2_STATUS\020\002\022\024\n\020FIR"
  "MWARE_VERSION\020\003\022\021\n\rSERIAL_NUMBER\020\004\022\n\n\006UP"
  "TIME\020\005\022\014\n\010DOWNTIME\020\006"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_gui_2ftext_5fid_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_gui_2ftext_5fid_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_gui_2ftext_5fid_2eproto_once;
static bool descriptor_table_gui_2ftext_5fid_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_gui_2ftext_5fid_2eproto = {
  &descriptor_table_gui_2ftext_5fid_2eproto_initialized, descriptor_table_protodef_gui_2ftext_5fid_2eproto, "gui/text_id.proto", 180,
  &descriptor_table_gui_2ftext_5fid_2eproto_once, descriptor_table_gui_2ftext_5fid_2eproto_sccs, descriptor_table_gui_2ftext_5fid_2eproto_deps, 0, 0,
  schemas, file_default_instances, TableStruct_gui_2ftext_5fid_2eproto::offsets,
  file_level_metadata_gui_2ftext_5fid_2eproto, 0, file_level_enum_descriptors_gui_2ftext_5fid_2eproto, file_level_service_descriptors_gui_2ftext_5fid_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_gui_2ftext_5fid_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_gui_2ftext_5fid_2eproto), true);
namespace gui {
namespace text_id {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TextId_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_gui_2ftext_5fid_2eproto);
  return file_level_enum_descriptors_gui_2ftext_5fid_2eproto[0];
}
bool TextId_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace text_id
}  // namespace gui
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
